spring:
  kafka:
    bootstrap-servers: ${app.kafka.host}:${app.kafka.port}
    producer:
      properties:
        spring.json.add.type.headers: false
    consumer:
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed